version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
image: Previous Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  version_prefix: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build_script:
  - ps: dotnet build src/Easify.Ef.sln
artifacts:
  - path: "**/*.nupkg"
    name: Package
deploy:
  - provider: NuGet
    api_key:
      secure: udBSWYCH7maFnr2SuJ3fs0ovxfFmmFpqumWSqvTDpHjLYbAW5Hdzf5DOQPf1YWO7
    on:
      branch: master
only_commits:
  files:
    - src/
