version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
image: Previous Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  version_prefix: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build_script:
  - ps: dotnet build src/Easify.Ef.sln
artifacts:
  - path: "**/*.nupkg"
    name: Package
deploy:
  - provider: NuGet
    api_key:
      secure: udBSWYCH7maFnr2SuJ3fs0ovxfFmmFpqumWSqvTDpHjLYbAW5Hdzf5DOQPf1YWO7
    on:
      branch: master
notifications:
  - provider: Webhook
    url: https://outlook.office.com/webhook/84db8641-d8a9-4b9d-b818-f1e4d4087ae5@31d4ce72-dfb2-4be8-b876-3278f8641754/IncomingWebhook/53369591d10d4af98801d3f6184b58fa/44a9a258-9ff2-4690-b260-aa79ba2b368b
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
only_commits:
  files:
    - src/
